### PR TITLE
Add ITF Support

### PR DESCRIPTION
**Pull request by v0l**
This also includes formatting and padding fixes.

I've replaced the usage of `BarCodeType` with an abstract class `BarCodeParams` which will allow custom params for each barcode type, which i believe is a change worth implementing for future expand-ability.

### CODE REVIEW

**Comment by v0l** [comment]
@bigship any thoughts/comments?

**Comment by bigship** [comment]
I have midterm exams this two weeks. Your solution seems good to me , I
will merge it to master

Thanks !

Kieran <notifications@github.com>于2019年10月24日 周四03:26写道：

**Comment by v0l** [comment]
I think i can add a backward compatible api too, dont commit this yet.

**Comment by bigship** [comment]
Sure, and adjust the README accordingly.

Kieran <notifications@github.com>于2019年10月24日 周四15:25写道：

**Comment by v0l** [comment]
I went with changing the version to 1.1.0 instead of 2.0.0 since its backward compatible, later this can be removed completely..

**Pull request merged**
